engines:
  duplications:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 20
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
ratings:
  paths:
      - "**.js"
exclude_paths:
- "build"
- "public"
- "models"
- .gitignore
- "/server/tests/"
- "node_modules/"
- "gulpfile.babel.js"
